// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeCweON-Cxc1796CiYdm6ZVzVA4XkYDm8',
    appId: '1:132470415583:android:eeed3ac8ba77891eba496a',
    messagingSenderId: '132470415583',
    projectId: 'kettik-19d03',
    storageBucket: 'kettik-19d03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqnpIXdAu6XCNeFdKwWvVvQxWCLvc9eBY',
    appId: '1:132470415583:ios:40c24b1b9af5eb83ba496a',
    messagingSenderId: '132470415583',
    projectId: 'kettik-19d03',
    storageBucket: 'kettik-19d03.appspot.com',
    androidClientId: '132470415583-4qp25ob7g3eod2oel8113ahh5cjnmfg7.apps.googleusercontent.com',
    iosClientId: '132470415583-qi8qlga777pqc368pd9qbsf3tg8iq7fm.apps.googleusercontent.com',
    iosBundleId: 'kz.kettik',
  );
}
