import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'kk_KZ:': {
          "helloWorld": "Қош келдіңіз",
          "sign_in_body": "WhatsApp телефон нөміріңізді енгізіңіз",
          "introTitle1": "Kettik қолданбасына қош келдіңіз!",
          "introTitle2":
              "Шұғыл түрде бір зат жіберу қажет болса, таптырмас шешім. \n Әрі, өзіңізге қосымша табыс көзі.",
          "introTitle3":
              "Әлемдік әйгілі дүкендерден тікелей тапсырыспен сатып алуға көмектесеміз.",
          "continueText": "Жалғастыру",
          "phone": "Телефон нөмірі",
          "phonePrompt": "Телефон нөміріңізді енгізіңіз",
          "password": "Құпия сөз",
          "passwordPrompt": "Құпия сөзіңізді енгізіңіз",
          "rememberMe": "Мені ұмытпаңыз",
          "forgot_password": "Құпия сөзді ұмыттыңыз ба",
          "dont_have_an_account": "Есептік жазбаңыз жоқ па?",
          "sign_up": "Тіркелу",
          "register_account": "Тіркелу",
          "register_account_desc": "Мәліметтеріңізді толтырыңыз",
          "terms_and_condition":
              "Жалғастыру арқылы біздің Шарттарымызбен \nжәне Құпиялық саясатымен келісесіз",
          "home": "Kettik",
          "profile": "Кабинет",
          "my_transactions": "Менің хабарландыруларым",
          "delete_account": "Аккаунтты жою",
          "help": "Көмек",
          "logout": "Шығу",
          "create_request": "Хабарландыру беру",
          "promo": "Жеңілдіктер",
          "promo_price": "Жеңілдікпен бағасы: ",
          "currency": " \$",
          "buyer": "Байер: ",
          "send_request": "Жазу",
          "sender": "Жіберушілер",
          "courier": "Курьерлер",
          "isender": "Жіберушімін",
          "icourier": "Курьермін",
          "ihint": "Таңдаңыз",
          "country": "Ел",
          "region": "Аймақ",
          "city": "Қала",
          "weight": "Салмағы(кг): ",
          "price": "Бағасы(\$)",
          "description": "Сипаттама",
          "send": "Хабарландыру беру",
          "name_label": "Сіздің атыңыз ",
          "name_hint": "Аты-жөні",
          "continue": "Жалғастыру",
          "deadline": "Мерзімі:",
          "internal_server_error":
              "Бірдеңе дұрыс болмады. Біз оны мүмкіндігінше тезірек жөндеуге тырысамыз.",
          "from": "Қайдан",
          "to": "Қайда",
          "kWrongRequestType": "Хабарландыру түрін таңдаңыз",
          "kNullCountryField": "Елді таңдаңыз",
          "kNullRegionField": "Аймақты таңдаңыз",
          "kNullCityField": "Қаланы таңдаңыз",
          "kNullToCountryField": "Жіберітін елді таңдаңыз",
          "kNullToRegionField": "Жіберітін аймақты таңдаңыз",
          "kNullToCityField": "Жіберітін қаланы таңдаңыз",
          "kNullWeightField": "Салмақты жазыныз",
          "kNullPriceField": "Бағасын жазыныз",
          "kNullNoteField": "Сипаттама жазыңыз",
          "alert_title": "Назар аударыңыз !",
          "alert_content":
              "Ақшаны алдын ала аударудан сақ болыңыз. Қолданба әкімшілігі бұл үшін жауапты емес, кабинетте біздің құпиялылық саясаты мен пайдалану шарттарын оқып шығыңыз.",
          "contact_us": "Бізбен байланысыңыз",
          "about": "Біз туралы",
          "terms": "Қолдану шарттары",
          "privacy_policy": "Құпиялылық саясаты",
          "we_have_sent_code":
              "Біз бір реттік пароль кодты SMS арқылы жібердік",
          "enter_code_below": "Төменге OTP кодын енгізіңіз",
          "next": "Келесі",
          "did_not_get_the_code": "Кодты алмадыңыз ба? ",
          "resend": "Қайта жіберу",
          "invalid_otp": "Жарамсыз код",
          "find": "Нәтижелерді көрсету",
          "filter": "Іздеу",
          "from_value": "бастап",
          "to_value": "дейін"
        },
        'en_US': {
          "helloWorld": "Welcome",
          "sign_in_body": "Sign in with your WhatsApp phone number or register",
          "introTitle1": "Welcome to Kettik App!",
          "introTitle2":
              "We help people find each other. \n Those who need to send something urgently and those who are ready to make money on it",
          "introTitle3":
              "You can order a purchase directly from a store from abroad",
          "continueText": "Continiue",
          "phone": "Phone number",
          "phonePrompt": "Enter your phone number",
          "password": "Password",
          "passwordPrompt": "Enter your password",
          "rememberMe": "Remember me",
          "forgot_password": "Forgot Password",
          "dont_have_an_account": "Don’t have an account?",
          "sign_up": "Sign Up",
          "register_account": "Register Account",
          "register_account_desc": "Please fill in all fields",
          "terms_and_condition":
              "By continuing your confirm that you agree \nwith our Term and Condition & Privacy Policy",
          "otp": "OTP Verification",
          "phone_verification": "Phone Verification",
          "we_have_sent_code":
              "We have sent SMS with One Time Password code to ",
          "enter_code_below": "Enter OTP code below",
          "next": "Next",
          "did_not_get_the_code": "Didn\'t get the code? ",
          "resend": "Resend",
          "home": "Kettik",
          "profile": "Account",
          "my_transactions": "My requests",
          "delete_account": "Delete account",
          "help": "Help",
          "logout": "Logout",
          "create_request": "Create request",
          "promo": "Discounts",
          "promo_price": "Discount price: ",
          "currency": " \$",
          "buyer": "Buyer: ",
          "send_request": "Chat",
          "sender": "Senders",
          "courier": "Couriers",
          "isender": "Sender",
          "icourier": "Courier",
          "ihint": "Select type",
          "country": "Country",
          "region": "Region",
          "city": "City",
          "weight": "Weight",
          "price": "Price",
          "description": "Description",
          "send": "Create",
          "name_label": "Your name ",
          "name_hint": "Name",
          "continue": "Continue",
          "deadline": "Deadline:",
          "internal_server_error":
              "Something went wrong. We're working on getting it fixed as soon as we can.",
          "from": "From",
          "to": "To",
          "kWrongRequestType": "Please select request type",
          "kNullCountryField": "Please select from country",
          "kNullRegionField": "Please select from region",
          "kNullCityField": "Please select from city",
          "kNullToCountryField": "Please select to country",
          "kNullToRegionField": "Please select to region",
          "kNullToCityField": "Please select to city",
          "kNullWeightField": "Please enter weight",
          "kNullPriceField": "Please enter price",
          "kNullNoteField": "Please write description",
          "alert_title": "Attention !",
          "alert_content":
              "Be careful do not transfer money in advance. The application is not responsible, please read our privacy policy and terms of use in your account.",
          "contact_us": "Contact us",
          "about": "About",
          "terms": "Terms and Conditions",
          "privacy_policy": "Privacy Policy",
          "invalid_otp": "Invalid OTP",
          "find": "Show results",
          "filter": "Filter",
          "from_value": "from",
          "to_value": "to"
        },
        'ru_KZ': {
          "helloWorld": "Қош келдіңіз",
          "sign_in_body": "WhatsApp телефон нөміріңізді енгізіңіз",
          "introTitle1": "Kettik қолданбасына қош келдіңіз!",
          "introTitle2":
              "Шұғыл түрде бір зат жіберу қажет болса, таптырмас шешім. Әрі, өзіңізге қосымша табыс көзі.",
          "introTitle3":
              "Әлемдік әйгілі дүкендерден тікелей тапсырыспен сатып алуға көмектесеміз.",
          "continueText": "Жалғастыру",
          "phone": "Телефон нөмірі",
          "phonePrompt": "Телефон нөміріңізді енгізіңіз",
          "password": "Құпия сөз",
          "passwordPrompt": "Құпия сөзіңізді енгізіңіз",
          "rememberMe": "Мені ұмытпаңыз",
          "forgot_password": "Құпия сөзді ұмыттыңыз ба",
          "dont_have_an_account": "Есептік жазбаңыз жоқ па?",
          "sign_up": "Тіркелу",
          "register_account": "Тіркелу",
          "register_account_desc": "Мәліметтеріңізді толтырыңыз",
          "terms_and_condition":
              "Жалғастыру арқылы біздің Шарттарымызбен \nжәне Құпиялық саясатымен келісесіз",
          "home": "Kettik",
          "profile": "Кабинет",
          "my_transactions": "Менің хабарландыруларым",
          "delete_account": "Аккаунтты жою",
          "we_have_sent_code":
              "Біз бір реттік пароль кодты SMS арқылы жібердік",
          "enter_code_below": "Төменге OTP кодын енгізіңіз",
          "next": "Келесі",
          "did_not_get_the_code": "Кодты алмадыңыз ба? ",
          "resend": "Қайта жіберу",
          "help": "Көмек",
          "logout": "Шығу",
          "create_request": "Хабарландыру беру",
          "promo": "Жеңілдіктер",
          "promo_price": "Жеңілдікпен бағасы: ",
          "currency": " \$",
          "buyer": "Байер: ",
          "send_request": "Жазу",
          "sender": "Жіберушілер",
          "courier": "Курьерлер",
          "isender": "Жіберушімін",
          "icourier": "Курьермін",
          "ihint": "Таңдаңыз",
          "country": "Ел",
          "region": "Аймақ",
          "city": "Қала",
          "weight": "Салмағы(кг): ",
          "price": "Бағасы(\$)",
          "description": "Сипаттама",
          "send": "Хабарландыру беру",
          "name_label": "Сіздің атыңыз ",
          "name_hint": "Аты-жөні",
          "continue": "Жалғастыру",
          "deadline": "Мерзімі:",
          "internal_server_error":
              "Бірдеңе дұрыс болмады. Біз оны мүмкіндігінше тезірек жөндеуге тырысамыз.",
          "from": "Қайдан",
          "to": "Қайда",
          "kWrongRequestType": "Хабарландыру түрін таңдаңыз",
          "kNullCountryField": "Елді таңдаңыз",
          "kNullRegionField": "Аймақты таңдаңыз",
          "kNullCityField": "Қаланы таңдаңыз",
          "kNullToCountryField": "Жіберітін елді таңдаңыз",
          "kNullToRegionField": "Жіберітін аймақты таңдаңыз",
          "kNullToCityField": "Жіберітін қаланы таңдаңыз",
          "kNullWeightField": "Салмақты жазыныз",
          "kNullPriceField": "Бағасын жазыныз",
          "kNullNoteField": "Сипаттама жазыңыз",
          "alert_title": "Назар аударыңыз !",
          "alert_content":
              "Ақшаны алдын ала аударудан сақ болыңыз. Қолданба әкімшілігі бұл үшін жауапты емес, кабинетте біздің құпиялылық саясаты мен пайдалану шарттарын оқып шығыңыз.",
          "contact_us": "Бізбен байланысыңыз",
          "about": "Біз туралы",
          "terms": "Қолдану шарттары",
          "privacy_policy": "Құпиялылық саясаты",
          "invalid_otp": "Жарамсыз код",
          "find": "Нәтижелерді көрсету",
          "filter": "Іздеу",
          "from_value": "бастап",
          "to_value": "дейін"
        },
        'ru_RU': {
          "helloWorld": "Добро пожаловать",
          "sign_in_body": "Введите ваш номер телефона c WhatsApp",
          "introTitle1": "Добро пожаловать в Kettik App !",
          "introTitle2":
              "Мы помогаем людям найти друг друга \n Тех кому нужно что то срочно отправить и тех кто готов на этом заработать",
          "introTitle3":
              "Вы можете заказать покупку напрямую с магазина из за рубежа",
          "continueText": "Продолжить",
          "phone": "Номер телефона",
          "phonePrompt": "Введите номер телефона",
          "password": "Пароль",
          "passwordPrompt": "Введите свой пароль",
          "rememberMe": "Запомните меня",
          "forgot_password": "Забыл пароль",
          "dont_have_an_account": "У вас нет аккаунта?",
          "sign_up": "Зарегистрироваться",
          "register_account": "Регистрация",
          "register_account_desc":
              "Заполните свои данные или продолжите \n через социальные сети",
          "terms_and_condition":
              "Продолжая вы подтверждаете, что вы согласны\nс нашими Условиями и Политикой конфиденциальности",
          "otp": "Проверка одноразового пароля",
          "phone_verification": "Верификация",
          "we_have_sent_code":
              "Мы отправили SMS с одноразовым паролем на номер ",
          "enter_code_below": "Введите код OTP ниже",
          "next": "Далее",
          "did_not_get_the_code": "Не получили код?",
          "resend": "Отправить повторно",
          "sender": "Отправители",
          "courier": "Курьеры",
          "isender": "Я отправитель",
          "icourier": "Я курьер",
          "home": "Kettik",
          "profile": "Кабинет",
          "from": "Откуда",
          "to": "Куда",
          "wight": "Вec: ",
          "send_request": "Написать",
          "my_transactions": "Мой объявления",
          "delete_account": "Удалить аккаунт",
          "help": "Помощь",
          "logout": "Выйти",
          "create_request": "Подать объявление",
          "promo": "Акции",
          "promo_price": "Цена со скидкой: ",
          "currency": " \$",
          "buyer": "Байер: ",
          "ihint": "Выберите тип",
          "country": "Страна",
          "region": "Область",
          "city": "Город",
          "weight": "Вес",
          "price": "Цена",
          "description": "Описание",
          "send": "Создать",
          "name_label": "Ваше имя ",
          "name_hint": "Имя",
          "continue": "Продолжить",
          "deadline": "Крайний срок:",
          "internal_server_error":
              "Что-то пошло не так. Мы работаем над тем, чтобы исправить это, как только сможем.",
          "kWrongRequestType": "Выберите тип запроса",
          "kNullCountryField": "Пожалуйста выберите страну отправки",
          "kNullRegionField": "Пожалуйста выберите регион отправки",
          "kNullCityField": "Пожалуйста выберите город отправки",
          "kNullToCountryField": "Пожалуйста выберите страну доставки",
          "kNullToRegionField": "Пожалуйста выберите регион доставки",
          "kNullToCityField": "Пожалуйста выберите город доставки",
          "kNullWeightField": "Пожалуйста введите вес посылки",
          "kNullPriceField": "Пожалуйста введите цену за доставку",
          "kNullNoteField": "Пожалуйста напишитие описание посылки",
          "alert_title": "Внимание !",
          "alert_content":
              "Будьте осторожны, не переводите деньги заранее. Приложение не несет ответственности, ознакомьтесь с нашей политикой конфиденциальности и условиями использования в личном кабинете.",
          "contact_us": "Свяжитесь с нами",
          "about": "О нас",
          "terms": "Условия использования",
          "privacy_policy": "Политика конфиденциальности",
          "invalid_otp": "Недействительный одноразовый пароль",
          "find": "Показать результаты",
          "filter": "Фильтр",
          "from_value": "от",
          "to_value": "до"
        }
      };
}
